# dev config

[env]
env = "dev"

[database]
#dsn="root:Xieyuhao19990429@tcp(127.0.0.1:3306)/project_management?charset=utf8&parseTime=True&loc=Local"
user = "root"
passWord = "zhangyinge"
dbName = "project_management"
server = "127.0.0.1"
ports = 3306

[database.connection]
maxIdleConn = 10
maxOpenConn = 100
#空闲等待时间 5min
connMaxIdleTime = 30000

